# Generated by Django 4.1.4 on 2023-01-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_owner', models.IntegerField()),
                ('cart_quantity', models.IntegerField()),
                ('cart_prodId', models.IntegerField()),
                ('cart_price', models.CharField(max_length=225)),
                ('cart_category', models.CharField(max_length=225)),
                ('cart_image', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'tbl_cart',
            },
        ),
    ]
