# Generated by Django 4.1.4 on 2023-01-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_image',
            field=models.CharField(max_length=225),
        ),
    ]
