# Generated by Django 4.1.4 on 2023-01-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_cart_cart_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=225)),
                ('order_product', models.CharField(max_length=225)),
                ('order_price', models.CharField(max_length=225)),
                ('order_img', models.CharField(max_length=225)),
                ('order_phone', models.IntegerField()),
                ('order_address', models.CharField(max_length=225)),
                ('order_quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_order',
            },
        ),
    ]
