# Generated by Django 4.1.4 on 2023-01-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_prodowner',
            field=models.IntegerField(null=True),
        ),
    ]
