# Generated by Django 4.1.4 on 2023-01-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orders_order_prodowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_price',
            field=models.IntegerField(),
        ),
    ]
